name: Generate UML
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  generate-uml:
    runs-on: ubuntu-latest
    steps:
      - uses: pollyannagogolook/AutoUmlDrawer@v1.0.2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          entryPoint: "python"
          args: "/app/src/main.py"